"""Change id to UUID

Revision ID: 17c5cd257da9
Revises: 81e93ac23a75
Create Date: 2024-11-08 17:57:06.277448

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '17c5cd257da9'
down_revision: Union[str, None] = '81e93ac23a75'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('TB_SIMULATIONS',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('iterationsNumber', sa.Integer(), nullable=True),
    sa.Column('gridSize', sa.Integer(), nullable=True),
    sa.Column('ingredients', sa.JSON(), nullable=True),
    sa.Column('parameters', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_TB_SIMULATIONS_name'), 'TB_SIMULATIONS', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_TB_SIMULATIONS_name'), table_name='TB_SIMULATIONS')
    op.drop_table('TB_SIMULATIONS')
    # ### end Alembic commands ###
