"""Change gridSize to gridLenght and gridHeight

Revision ID: 1cb6af8aea39
Revises: e896df2c8fab
Create Date: 2024-11-14 20:19:49.145753

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1cb6af8aea39'
down_revision: Union[str, None] = 'e896df2c8fab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('TB_SIMULATIONS', sa.Column('gridLenght', sa.Integer(), nullable=False))
    op.add_column('TB_SIMULATIONS', sa.Column('gridHeight', sa.Integer(), nullable=False))
    op.drop_column('TB_SIMULATIONS', 'gridSize')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('TB_SIMULATIONS', sa.Column('gridSize', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('TB_SIMULATIONS', 'gridHeight')
    op.drop_column('TB_SIMULATIONS', 'gridLenght')
    # ### end Alembic commands ###
