"""Create simulations table

Revision ID: 359ff99e6a75
Revises: 
Create Date: 2024-11-08 16:29:26.990323

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '359ff99e6a75'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tb_simulations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('iterationsNumber', sa.Integer(), nullable=True),
    sa.Column('gridDimension', sa.Integer(), nullable=True),
    sa.Column('ingredients', sa.JSON(), nullable=True),
    sa.Column('parameters', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tb_simulations_id'), 'tb_simulations', ['id'], unique=False)
    op.create_index(op.f('ix_tb_simulations_name'), 'tb_simulations', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tb_simulations_name'), table_name='tb_simulations')
    op.drop_index(op.f('ix_tb_simulations_id'), table_name='tb_simulations')
    op.drop_table('tb_simulations')
    # ### end Alembic commands ###
