"""Adding created_at and updated_at columns

Revision ID: 77d2f2fcda81
Revises: bb48619b0578
Create Date: 2024-11-13 17:11:38.194350

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '77d2f2fcda81'
down_revision: Union[str, None] = 'bb48619b0578'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('TB_SIMULATIONS', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('TB_SIMULATIONS', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('TB_SIMULATIONS', 'updated_at')
    op.drop_column('TB_SIMULATIONS', 'created_at')
    # ### end Alembic commands ###
