"""Add reactions column

Revision ID: 780731ea7764
Revises: 1cb6af8aea39
Create Date: 2025-04-09 20:59:27.848657

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '780731ea7764'
down_revision: Union[str, None] = '1cb6af8aea39'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('TB_SIMULATIONS', sa.Column('reactions', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('TB_SIMULATIONS', 'reactions')
    # ### end Alembic commands ###
