"""Create TB_SIMULATIONS table

Revision ID: 81e93ac23a75
Revises: 359ff99e6a75
Create Date: 2024-11-08 16:46:12.262742

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '81e93ac23a75'
down_revision: Union[str, None] = '359ff99e6a75'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('TB_SIMULATIONS',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('iterationsNumber', sa.Integer(), nullable=True),
    sa.Column('gridSize', sa.Integer(), nullable=True),
    sa.Column('ingredients', sa.JSON(), nullable=True),
    sa.Column('parameters', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_TB_SIMULATIONS_id'), 'TB_SIMULATIONS', ['id'], unique=False)
    op.create_index(op.f('ix_TB_SIMULATIONS_name'), 'TB_SIMULATIONS', ['name'], unique=False)
    op.drop_index('ix_tb_simulations_id', table_name='tb_simulations')
    op.drop_index('ix_tb_simulations_name', table_name='tb_simulations')
    op.drop_table('tb_simulations')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tb_simulations',
    sa.Column('id', sa.UUID(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('iterationsNumber', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('gridDimension', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('ingredients', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('parameters', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='tb_simulations_pkey')
    )
    op.create_index('ix_tb_simulations_name', 'tb_simulations', ['name'], unique=False)
    op.create_index('ix_tb_simulations_id', 'tb_simulations', ['id'], unique=False)
    op.drop_index(op.f('ix_TB_SIMULATIONS_name'), table_name='TB_SIMULATIONS')
    op.drop_index(op.f('ix_TB_SIMULATIONS_id'), table_name='TB_SIMULATIONS')
    op.drop_table('TB_SIMULATIONS')
    # ### end Alembic commands ###
