"""Add rotation column

Revision ID: e1ed25c83c80
Revises: 72852529f8da
Create Date: 2025-05-08 19:10:17.723630

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e1ed25c83c80'
down_revision: Union[str, None] = '72852529f8da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('TB_SIMULATIONS', sa.Column('rotation', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('TB_SIMULATIONS', 'rotation')
    # ### end Alembic commands ###
