/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as SimulationsIndexImport } from './routes/simulations/index'
import { Route as SimulationsSimulationIdImport } from './routes/simulations/$simulationId'

// Create Virtual Routes

const AboutLazyImport = createFileRoute('/about')()

// Create/Update Routes

const AboutLazyRoute = AboutLazyImport.update({
  path: '/about',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/about.lazy').then((d) => d.Route))

const SimulationsIndexRoute = SimulationsIndexImport.update({
  path: '/simulations/',
  getParentRoute: () => rootRoute,
} as any)

const SimulationsSimulationIdRoute = SimulationsSimulationIdImport.update({
  path: '/simulations/$simulationId',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutLazyImport
      parentRoute: typeof rootRoute
    }
    '/simulations/$simulationId': {
      id: '/simulations/$simulationId'
      path: '/simulations/$simulationId'
      fullPath: '/simulations/$simulationId'
      preLoaderRoute: typeof SimulationsSimulationIdImport
      parentRoute: typeof rootRoute
    }
    '/simulations/': {
      id: '/simulations/'
      path: '/simulations'
      fullPath: '/simulations'
      preLoaderRoute: typeof SimulationsIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/about': typeof AboutLazyRoute
  '/simulations/$simulationId': typeof SimulationsSimulationIdRoute
  '/simulations': typeof SimulationsIndexRoute
}

export interface FileRoutesByTo {
  '/about': typeof AboutLazyRoute
  '/simulations/$simulationId': typeof SimulationsSimulationIdRoute
  '/simulations': typeof SimulationsIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/about': typeof AboutLazyRoute
  '/simulations/$simulationId': typeof SimulationsSimulationIdRoute
  '/simulations/': typeof SimulationsIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/about' | '/simulations/$simulationId' | '/simulations'
  fileRoutesByTo: FileRoutesByTo
  to: '/about' | '/simulations/$simulationId' | '/simulations'
  id: '__root__' | '/about' | '/simulations/$simulationId' | '/simulations/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  AboutLazyRoute: typeof AboutLazyRoute
  SimulationsSimulationIdRoute: typeof SimulationsSimulationIdRoute
  SimulationsIndexRoute: typeof SimulationsIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  AboutLazyRoute: AboutLazyRoute,
  SimulationsSimulationIdRoute: SimulationsSimulationIdRoute,
  SimulationsIndexRoute: SimulationsIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/about",
        "/simulations/$simulationId",
        "/simulations/"
      ]
    },
    "/about": {
      "filePath": "about.lazy.tsx"
    },
    "/simulations/$simulationId": {
      "filePath": "simulations/$simulationId.tsx"
    },
    "/simulations/": {
      "filePath": "simulations/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
