@baseUrl = http://localhost:8000
@simulation_id = e3746600-4945-4e49-b527-04272d625d5c

GET {{baseUrl}}/simulations

###

POST {{baseUrl}}/simulations
Content-Type: application/json; charset=utf-8

{
  "name": "Simulação aaa",
  "iterationsNumber": 100,
  "gridSize": 50,
  "ingredients": [
    {
      "name": "Water",
      "initialNumber": 10,
      "color": "blue"
    }
  ],
  "parameters": {
    "Pm": [1.0],
    "Pb": [
      {
        "relation": "AA",
        "value": 1.0
      }
    ],
    "J": [
      {
        "relation": "AA",
        "value": 1.0
      }
    ]
  }
}

###

GET {{baseUrl}}/simulations/{{simulation_id}}/run
Content-Type: application/json; charset=utf-8

###

GET {{baseUrl}}/simulations/{{simulation_id}}
Content-Type: application/json; charset=utf-8

###

GET {{baseUrl}}/simulations/{{simulation_id}}/decompressed-iterations
Content-Type: application/json; charset=utf-8

###

GET {{baseUrl}}/simulations/{{simulation_id}}/results
Content-Type: application/json; charset=utf-8